spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "dlRQWJrpkt71ooEzYwMiCxhWN5ntDcTUPQwj1xGL4Hw="
  expiration-ms: 86400000

